version: '3'
services:
    todo-view-next-dev:
        image: ayataka0nk/todo-view-next-dev:master
        volumes:
            - todo-view-next-dev:/workspace
        ports:
            - '127.0.0.1:18080:3000'
        working_dir: /workspace
        tty: true
        command: >
            sh -c '
                git config --global user.email "$GIT_USER_EMAIL" &&
                git config --global user.name "$GIT_USER_NAME" &&
                sh'
volumes:
    todo-view-next-dev:
        driver: local
