version: '3'
services:
  dev:
    image: ayataka0nk/next-todo-dev:latest
    volumes:
      - next-todo-dev:/root/workspace
      - ./id_rsa:/required/id_rsa
    tty: true
    working_dir: /root/workspace
    ports:
      - "127.0.0.1:9000:8000"
      - "127.0.0.1:3000:3000"
    environment: 
      GIT_USER_EMAIL: $GIT_USER_EMAIL
      GIT_USER_NAME: $GIT_USER_NAME
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - next-todo-dev-db:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8100:8080

volumes:
  next-todo-dev:
    driver: local
  next-todo-dev-db:
    driver: local