version: '3'
services:
  dev:
    image: ayataka0nk/next-todo-dev:0.1.0
    volumes:
      - next-todo-dev:/workspace
      - ./optionfiles:/optionfiles
    tty: true
    working_dir: /workspace
    command: >
      bash -c '
      mkdir /root/.ssh &&
      chmod 700 /root/.ssh &&
      cp -R /optionfiles/id_rsa /root/.ssh/id_rsa &&
      chmod 600 /root/.ssh/id_rsa &&
      git config --global user.email "$GIT_USER_EMAIL" &&
      git config --global user.name "$GIT_USER_NAME" &&
      /bin/bash'
volumes:
  next-todo-dev:
    driver: local
  