version: '3'
services:
    next-todo-api:
        image: ayataka0nk/next-todo-api-prod:master
        networks:
            - front
    next-todo-view:
        image: ayataka0nk/next-todo-view-prod:master
        ports:
            - "8080:3000"
        networks:
            - front
networks:
    front:
        driver: bridge
    back:
        driver: bridge