version: "3"
services:
    todo-api-express:
        image: ayataka0nk/todo-api-express:master
        ports:
            - "8090:3000"
        networks:
            - front
    next-view-next:
        image: ayataka0nk/todo-view-next:master
        ports:
            - "8080:3000"
        environment:
            ORMCONFIG_HOST: db
            ORMCONFIG_PORT: 3306
            ORMCONFIG_USERNAME: todoapp
            ORMCONFIG_PASSWORD: $ORMCONFIG_PASSWORD
        networks:
            - front
            - back
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: todoapp
            MYSQL_USER: todoapp
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        volumes:
            - todo-db:/var/lib/mysql
        networks:
            - back
    adminer:
        image: adminer
        ports:
            - 8100:8080
        networks:
            - back
volumes:
    todo-db:
        driver: local
networks:
    front:
        driver: bridge
    back:
        driver: bridge
